const STORE_SEARCH_PARAM = 'STORE_SEARCH_PARAM'
const STORE_SEARCH_RESULT = 'STORE_SEARCH_RESULT'
const STORE_MOVIE = 'STORE_MOVIE'
const LOAD_MORE_MOVIE = 'LOAD_MORE_MOVIE'
const STORE_LOAD_MORE = 'STORE_LOAD_MORE'

export { STORE_SEARCH_PARAM, STORE_SEARCH_RESULT, STORE_MOVIE, LOAD_MORE_MOVIE, STORE_LOAD_MORE }